name: Scheduled
on:
  schedule:
    - cron:  '*/10 * * * *'    # Every 10 mins to verify schedule runner

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Print Time
        run: |
          echo "Hello"
          echo "$(date '+%Y%m%d%H%M')"