name: PR Validator - Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: get_app_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Commit Version
        id: commit_version
        run: |
          git checkout -b send-minimal-notification
          git config user.name github-actions
          git config user.email noreply@github.com
          git add .github/workflows/e2e_nightly.yaml
          git add .github/workflows/~reusable_public_publish.yaml
          git diff --staged --quiet && (echo "pushVersion=false" >> $GITHUB_OUTPUT) || (git commit -m "Updating version" --no-verify && git push origin bump-version-"$VERSION_NUMBER" --no-verify && echo "pushVersion=true" >> $GITHUB_OUTPUT)
      - name: Create PR for version
        if: steps.commit_version.outputs.pushVersion == 'true'
        run: |
          gh pr create --base main --title "Update version" --body "Update version"
        env:
          GITHUB_TOKEN: ${{ steps.get_app_token.outputs.token }}

  